# Generated by Django 4.1.4 on 2023-01-07 13:05

import apps.users.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('activity', models.CharField(blank=True, max_length=225, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.users.utils.user_company_image_upload_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('visit_website_url_name', models.CharField(blank=True, max_length=225, null=True)),
                ('visit_website_url', models.URLField(blank=True, null=True)),
                ('address_url', models.URLField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_company',
            },
        ),
    ]
