# Generated by Django 4.1.4 on 2023-01-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='back_account',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userbankcart',
            name='back_cart',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
