# Generated by Django 4.1.4 on 2023-01-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_alter_userbankaccount_back_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='is_avatar',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='is_background',
        ),
    ]
