# Generated by Django 4.1.4 on 2023-01-07 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Last_name')),
                ('full_name', models.CharField(blank=True, max_length=225, null=True, verbose_name='Full_name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('in_archive', models.BooleanField(default=False, verbose_name='In Archive')),
            ],
            options={
                'verbose_name': 'ContactUs',
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('emirate', models.CharField(max_length=255, verbose_name='Эмираты')),
                ('street_address', models.TextField(verbose_name='Street address')),
                ('apartment_entrance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apartment_entrance')),
                ('house', models.CharField(max_length=255, verbose_name='House/Apartment')),
                ('order_notes', models.TextField(blank=True, null=True, verbose_name='Order Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('in_archive', models.BooleanField(default=False, verbose_name='In Archive')),
                ('choices', models.PositiveSmallIntegerField(choices=[(100, 'CASH_DELIVERY'), (110, 'BY_CARD')], default=110, verbose_name='Формат выбора оплаты')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Basket')),
            ],
            options={
                'verbose_name': 'Checkout',
                'verbose_name_plural': 'Checkouts',
            },
        ),
    ]
